app register --name aggregate-counter --type sink --uri maven://org.springframework.cloud.stream.app:aggregate-counter-sink:jar:exec:1.0.1.RELEASE
app register --name cassandra --type sink --uri maven://org.springframework.cloud.stream.app:cassandra-sink:jar:exec:1.0.1.RELEASE
app register --name counter --type sink --uri maven://org.springframework.cloud.stream.app:counter-sink:jar:exec:1.0.1.RELEASE
app register --name field-value-counter --type sink --uri maven://org.springframework.cloud.stream.app:field-value-counter-sink:jar:exec:1.0.1.RELEASE
app register --name file --type sink --uri maven://org.springframework.cloud.stream.app:file-sink:jar:exec:1.0.1.RELEASE
app register --name ftp --type sink --uri maven://org.springframework.cloud.stream.app:ftp-sink:jar:exec:1.0.1.RELEASE
app register --name gemfire --type sink --uri maven://org.springframework.cloud.stream.app:gemfire-sink:jar:exec:1.0.1.RELEASE
app register --name gpfdist --type sink --uri maven://org.springframework.cloud.stream.app:gpfdist-sink:jar:exec:1.0.1.RELEASE
app register --name hdfs --type sink --uri maven://org.springframework.cloud.stream.app:hdfs-sink:jar:exec:1.0.1.RELEASE
app register --name jdbc --type sink --uri maven://org.springframework.cloud.stream.app:jdbc-sink:jar:exec:1.0.1.RELEASE
app register --name log --type sink --uri maven://org.springframework.cloud.stream.app:log-sink:jar:exec:1.0.1.RELEASE
app register --name rabbit --type sink --uri maven://org.springframework.cloud.stream.app:rabbit-sink:jar:exec:1.0.1.RELEASE
app register --name redis --type sink --uri maven://org.springframework.cloud.stream.app:redis-sink:jar:exec:1.0.1.RELEASE
app register --name router --type sink --uri maven://org.springframework.cloud.stream.app:router-sink:jar:exec:1.0.1.RELEASE
app register --name tcp --type sink --uri maven://org.springframework.cloud.stream.app:tcp-sink:jar:exec:1.0.1.RELEASE
app register --name throughput --type sink --uri maven://org.springframework.cloud.stream.app:throughput-sink:jar:exec:1.0.1.RELEASE
app register --name websocket --type sink --uri maven://org.springframework.cloud.stream.app:websocket-sink:jar:exec:1.0.1.RELEASE
app register --name timestamp --type task --uri maven://org.springframework.cloud.task.app:timestamp-task:jar:exec:1.0.1.RELEASE
