app register --name file --type source --uri maven://org.springframework.cloud.stream.app:file-source:jar:exec:1.0.1.RELEASE
app register --name ftp --type source --uri maven://org.springframework.cloud.stream.app:ftp-source:jar:exec:1.0.1.RELEASE
app register --name jdbc --type source --uri maven://org.springframework.cloud.stream.app:jdbc-source:jar:exec:1.0.1.RELEASE
app register --name jms --type source  --uri maven://org.springframework.cloud.stream.app:jms-source:jar:exec:1.0.1.RELEASE
app register --name http --type source --uri maven://org.springframework.cloud.stream.app:http-source:jar:exec:1.0.1.RELEASE
app register --name load-generator --type source --uri maven://org.springframework.cloud.stream.app:load-generator-source:jar:exec:1.0.1.RELEASE
app register --name rabbit --type source --uri maven://org.springframework.cloud.stream.app:rabbit-source:jar:exec:1.0.1.RELEASE
app register --name sftp --type source --uri maven://org.springframework.cloud.stream.app:sftp-source:jar:exec:1.0.1.RELEASE
app register --name tcp --type source --uri maven://org.springframework.cloud.stream.app:tcp-source:jar:exec:1.0.1.RELEASE
app register --name time --type source --uri maven://org.springframework.cloud.stream.app:time-source:jar:exec:1.0.1.RELEASE
app register --name trigger --type source --uri maven://org.springframework.cloud.stream.app:trigger-source:jar:exec:1.0.1.RELEASE
app register --name twitterstream --type source --uri maven://org.springframework.cloud.stream.app:twitterstream-source:jar:exec:1.0.1.RELEASE
